// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu9_vbBjle-TnTKsdWhklk3WU8Ltj1X3k',
    appId: '1:921251262968:android:3f71d5f3f14b2d556ce60d',
    messagingSenderId: '921251262968',
    projectId: 'fcds-announcements-7dbbd',
    storageBucket: 'fcds-announcements-7dbbd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5Q16atln1kIi3w81pVATpJQnbV5PcU-w',
    appId: '1:921251262968:ios:b6b3ae8b9d4a4e816ce60d',
    messagingSenderId: '921251262968',
    projectId: 'fcds-announcements-7dbbd',
    storageBucket: 'fcds-announcements-7dbbd.firebasestorage.app',
    androidClientId: '921251262968-s1gmppeocm30iiokgmuj6c893d0fi4he.apps.googleusercontent.com',
    iosClientId: '921251262968-q1r3pql47o1gstej8ea4mepoem3o3edv.apps.googleusercontent.com',
    iosBundleId: 'com.TeamMaterials.fcdsAnnouncements',
  );
}
